server:
  port: 4400

#Local Mysql DB Config
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: SPRING_DATASOURCE_URL
    username: SPRING_DATASOURCE_USERNAME
    password: SPRING_DATASOURCE_PASSWORD
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss' #date received format
    serialization:
      FAIL_ON_EMPTY_BEANS: false